//Auth Actions
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//Orders Actions
export const ORDER_SUMMARY = "ORDER_SUMMARY";
export const INCREMENT_IMAGES = "INCREMENT_IMAGES";
export const DECREMENT_IMAGES = "DECREMENT_IMAGES";
export const SWITCH_TEMPLATE_ID = "SWITCH_TEMPLATE_ID";
export const CREATE_ORDER = "CREATE_ORDER";
export const ORDERS_FAILED = "ORDERS_FAILED";
export const ORDERS_LOADING = "ORDERS_LOADING";
export const CLEAR_ORDER_BUFFER = "CLEAR_ORDER_BUFFER";
export const ORDER_SUBMITTED = "ORDER_SUBMITTED";

//Templates Actions
export const SET_RECENT_TEMPLATES = "SET_RECENT_TEMPLATES";
export const TEMPLATES_FAILED = "TEMPLATES_FAILED";
export const TEMPLATES_LOADING = "TEMPLATES_LOADING";
export const CHANGE_TEMPLATE_BACKGROUND = "CHANGE_TEMPLATE_BACKGROUND";

export const ADVANCED_TEMPLATE_CHARGES = "ADVANCED_TEMPLATE_CHARGES";

export const SERVER_ERROR = "SERVER_ERROR";
export const INCREMENT_ORDER_FORM_STEP = "INCREMENT_ORDER_FORM_STEP";
export const DECREMENT_ORDER_FORM_STEP = "DECREMENT_ORDER_FORM_STEP";
